#!/bin/sh
#
# Build fsck_ext4fs outside the source tree, create disposable ext4 images,
# and exercise JBD2 recovery generated by e2fsprogs debugfs.
#
# JOURNAL_SEED reproduces randomized choices.  RANDOM_CASES and
# MUTATION_CASES control the randomized workload, FSCK_TIMEOUT bounds each
# checker invocation, and KEEP_TMP=1 retains generated fixtures.

set -eu

MKE2FS=${MKE2FS:-mke2fs}
DEBUGFS=${DEBUGFS:-debugfs}
E2FSCK=${E2FSCK:-e2fsck}
MAKE=${MAKE:-make}
CC=${CC:-cc}
TIMEOUT=${TIMEOUT:-timeout}
FSCK_TIMEOUT=${FSCK_TIMEOUT:-20}
JOURNAL_SEED=${JOURNAL_SEED:-260921}
RANDOM_CASES=${RANDOM_CASES:-6}
MUTATION_CASES=${MUTATION_CASES:-18}
JOURNAL_TEST_MODE=${JOURNAL_TEST_MODE:-all}
VNCONFIG=${VNCONFIG:-vnconfig}
MOUNT_EXT4FS=${MOUNT_EXT4FS:-mount_ext4fs}
UMOUNT=${UMOUNT:-umount}

case "$JOURNAL_TEST_MODE" in
all|kernel) ;;
*)	echo "JOURNAL_TEST_MODE must be 'all' or 'kernel'" >&2
	exit 1
	;;
esac

for tool in "$MKE2FS" "$DEBUGFS" "$E2FSCK" "$TIMEOUT" \
    sha256 dd tr cmp cp awk grep sed od; do
	if ! command -v "$tool" >/dev/null 2>&1; then
		echo "SKIPPED: fsck_ext4fs journal regress requires $tool"
		exit 0
	fi
done

if [ "$JOURNAL_TEST_MODE" = kernel ]; then
	for tool in "$VNCONFIG" "$MOUNT_EXT4FS" "$UMOUNT" "$CC" id; do
		if ! command -v "$tool" >/dev/null 2>&1; then
			echo "SKIPPED: kernel journal regress requires $tool"
			exit 0
		fi
	done
	if [ "$(id -u)" -ne 0 ]; then
		echo "SKIPPED: kernel journal regress must run as root"
		exit 0
	fi
fi

case "$FSCK_TIMEOUT:$JOURNAL_SEED:$RANDOM_CASES:$MUTATION_CASES" in
*[!0-9:]*)	echo "timeout, seed, and case counts must be unsigned integers" >&2
	exit 1
	;;
esac
[ "$FSCK_TIMEOUT" -gt 0 ] || { echo "FSCK_TIMEOUT must be positive" >&2; exit 1; }
[ "$JOURNAL_SEED" -le 2147483647 ] || { echo "JOURNAL_SEED is too large" >&2; exit 1; }
[ "$RANDOM_CASES" -le 32 ] || { echo "RANDOM_CASES is too large" >&2; exit 1; }
[ "$MUTATION_CASES" -le 96 ] || { echo "MUTATION_CASES is too large" >&2; exit 1; }
RNG_STATE=$JOURNAL_SEED
ulimit -c 0

KERNEL_VND=
KERNEL_MOUNTPOINT=
KERNEL_MOUNTED=0

work=$(mktemp -d /tmp/fsck_ext4fs_journal.XXXXXXXX)
case "$work" in
/tmp/fsck_ext4fs_journal.*) ;;
*)	echo "unsafe temporary directory: $work" >&2
	exit 1
	;;
esac

cleanup()
{
	rc=$?
	trap - EXIT HUP INT TERM
	if [ "$KERNEL_MOUNTED" -eq 1 ]; then
		run_privileged "$UMOUNT" "$KERNEL_MOUNTPOINT" >/dev/null 2>&1 || :
		KERNEL_MOUNTED=0
	fi
	if [ -n "$KERNEL_VND" ]; then
		run_privileged "$VNCONFIG" -u "$KERNEL_VND" >/dev/null 2>&1 || :
		KERNEL_VND=
	fi
	if [ "${KEEP_TMP:-0}" = 1 ] || [ "$rc" -ne 0 ]; then
		echo "temporary files retained in $work"
	else
		rm -rf "$work"
	fi
	exit "$rc"
}
trap cleanup EXIT HUP INT TERM

script_dir=$(CDPATH= cd "$(dirname "$0")" && pwd)
srcroot=$(CDPATH= cd "$script_dir/../../.." && pwd)

fail()
{
	echo "FAILED: $test_name: $*" >&2
	exit 1
}

ORPHAN_FIXTURE=
if [ "$JOURNAL_TEST_MODE" = kernel ]; then
	ORPHAN_FIXTURE=$work/orphan_fixture
	if ! "$CC" -Wall -Wextra -Werror -I"$srcroot/sys" \
	    "$script_dir/orphan_fixture.c" -o "$ORPHAN_FIXTURE" \
	    >"$work/orphan-fixture-build.log" 2>&1; then
		cat "$work/orphan-fixture-build.log" >&2
		test_name=build
		fail "could not build orphan fixture helper"
	fi
fi

run_privileged()
{
	[ "$(id -u)" -eq 0 ] || return 1
	"$@"
}

random_number()
{
	RNG_STATE=$(((RNG_STATE * 1103515245 + 12345) & 2147483647))
	RANDOM_VALUE=$RNG_STATE
}

if [ "$JOURNAL_TEST_MODE" = all ] && [ -z "${FSCK_EXT4FS:-}" ]; then
	objdir=$work/obj
	mkdir "$objdir"
	if ! MAKEOBJDIR="$objdir" "$MAKE" -s \
	    -C "$srcroot/sbin/fsck_ext4fs" >"$work/build.log" 2>&1; then
		cat "$work/build.log" >&2
		test_name=build
		fail "could not build fsck_ext4fs"
	fi
	FSCK_EXT4FS=$objdir/fsck_ext4fs
fi
if [ "$JOURNAL_TEST_MODE" = all ] && [ ! -x "$FSCK_EXT4FS" ]; then
	test_name=build
	fail "$FSCK_EXT4FS is not executable"
fi

create_image()
{
	image=$1
	block_size=$2
	CURRENT_BLOCK_SIZE=$block_size
	dd if=/dev/zero of="$image" bs=1m count=0 seek=64 status=none
	if ! "$MKE2FS" -q -F -t ext4 -b "$block_size" \
	    -O '^orphan_file' "$image" >"$case_dir/mke2fs.log" 2>&1; then
		cat "$case_dir/mke2fs.log" >&2
		fail "mke2fs failed"
	fi
}

create_orphan_file_image()
{
	image=$1
	block_size=$2
	CURRENT_BLOCK_SIZE=$block_size
	dd if=/dev/zero of="$image" bs=1m count=0 seek=64 status=none
	if ! "$MKE2FS" -q -F -t ext4 -b "$block_size" \
	    -O orphan_file "$image" >"$case_dir/mke2fs.log" 2>&1; then
		cat "$case_dir/mke2fs.log" >&2
		fail "mke2fs with orphan_file failed"
	fi
}

make_payload()
{
	file=$1
	block_size=$2
	blocks=$3
	byte=$4
	dd if=/dev/zero bs="$block_size" count="$blocks" status=none |
	    tr '\000' "$byte" >"$file"
}

make_random_payload()
{
	file=$1
	block_size=$2
	blocks=$3
	: >"$file"
	index=0
	while [ "$index" -lt "$blocks" ]; do
		random_number
		value=$((65 + RANDOM_VALUE % 26))
		octal=$(printf '%03o' "$value")
		byte=$(printf "\\$octal")
		dd if=/dev/zero bs="$block_size" count=1 status=none |
		    tr '\000' "$byte" >>"$file"
		index=$((index + 1))
	done
}

find_free_blocks()
{
	ff_image=$1
	ff_count=$2
	FREE_BLOCKS=$("$DEBUGFS" -R "find_free_block $ff_count" "$ff_image" \
	    2>/dev/null | sed -n 's/^Free blocks found:[[:space:]]*//p')
	set -- $FREE_BLOCKS
	[ "$#" -eq "$ff_count" ] || fail "could not find $ff_count free blocks"

	FREE_FIRST=$1
	FREE_LAST=$1
	expected=$1
	for block in "$@"; do
		case "$block" in
		*[!0-9]*|'') fail "debugfs returned a bad block number" ;;
		esac
		[ "$block" -eq "$expected" ] ||
		    fail "debugfs did not return consecutive free blocks"
		FREE_LAST=$block
		expected=$((expected + 1))
	done
	if [ "$ff_count" -eq 1 ]; then
		FREE_RANGE=$FREE_FIRST
	else
		FREE_RANGE=$FREE_FIRST-$FREE_LAST
	fi
}

run_debugfs()
{
	image=$1
	commands=$2
	if ! "$DEBUGFS" -w -f "$commands" "$image" \
	    >"$case_dir/debugfs.log" 2>&1; then
		cat "$case_dir/debugfs.log" >&2
		fail "debugfs failed"
	fi
}

run_fsck()
{
	mode=$1
	image=$2
	log=$3
	if "$TIMEOUT" -k 2 "$FSCK_TIMEOUT" "$FSCK_EXT4FS" "$mode" \
	    "$image" >"$log" 2>&1; then
		FSCK_STATUS=0
	else
		FSCK_STATUS=$?
	fi
	case "$FSCK_STATUS" in
	124|137)	fail "fsck_ext4fs exceeded ${FSCK_TIMEOUT}s timeout" ;;
	1[2-9][0-9]|[2-9][0-9][0-9])
		fail "fsck_ext4fs terminated abnormally (status $FSCK_STATUS)"
		;;
	esac
}

replay()
{
	image=$1
	if [ "$JOURNAL_TEST_MODE" = kernel ]; then
		kernel_replay "$image"
		return
	fi
	run_fsck -fy "$image" "$case_dir/fsck.log"
	if [ "$FSCK_STATUS" -ne 0 ]; then
		cat "$case_dir/fsck.log" >&2
		fail "fsck_ext4fs rejected a valid journal (status $FSCK_STATUS)"
	fi
	grep -q 'journal replay complete' "$case_dir/fsck.log" ||
	    fail "fsck_ext4fs did not report completed replay"
}

verify_e2fsck()
{
	image=$1
	if ! "$E2FSCK" -fn "$image" >"$case_dir/e2fsck.log" 2>&1; then
		cat "$case_dir/e2fsck.log" >&2
		fail "e2fsck rejected the recovered image"
	fi
}

compare_blocks()
{
	image=$1
	block_size=$2
	first=$3
	count=$4
	expected=$5
	dd if="$image" bs="$block_size" skip="$first" count="$count" \
	    status=none | cmp -s - "$expected" ||
	    fail "replayed home block contents differ"
}

journal_block()
{
	jb_image=$1
	jb_logical=$2
	JOURNAL_BLOCK=$("$DEBUGFS" -R "bmap <8> $jb_logical" "$jb_image" \
	    2>/dev/null | awk 'NF { value = $NF } END { print value }')
	case "$JOURNAL_BLOCK" in
	*[!0-9]*|'') fail "could not map journal block $jb_logical" ;;
	esac
}

read_be32_journal()
{
	image=$1
	logical=$2
	within=$3
	journal_block "$image" "$logical"
	offset=$((JOURNAL_BLOCK * CURRENT_BLOCK_SIZE + within))
	set -- $(dd if="$image" bs=1 skip="$offset" count=4 status=none |
	    od -An -tu1)
	[ "$#" -eq 4 ] || fail "could not read journal word"
	JOURNAL_WORD=$((($1 << 24) | ($2 << 16) | ($3 << 8) | $4))
}

read_le32_image()
{
	le_image=$1
	le_offset=$2
	set -- $(dd if="$le_image" bs=1 skip="$le_offset" count=4 \
	    status=none | od -An -tu1)
	[ "$#" -eq 4 ] || fail "could not read little-endian image word"
	IMAGE_WORD=$(($1 | ($2 << 8) | ($3 << 16) | ($4 << 24)))
}

write_byte()
{
	byte_image=$1
	byte_offset=$2
	byte_value=$3
	[ "$byte_value" -ge 0 ] && [ "$byte_value" -le 255 ] ||
	    fail "byte value is out of range"
	byte_octal=$(printf '%03o' "$byte_value")
	printf "\\$byte_octal" | dd of="$byte_image" bs=1 seek="$byte_offset" count=1 \
	    conv=notrunc status=none
}

flip_image_byte()
{
	fib_image=$1
	fib_offset=$2
	fib_mask=$3
	fib_value=$(dd if="$fib_image" bs=1 skip="$fib_offset" count=1 \
	    status=none | od -An -tu1 | awk 'NF { print $1 + 0 }')
	case "$fib_value" in
	*[!0-9]*|'') fail "could not read image byte" ;;
	esac
	write_byte "$fib_image" "$fib_offset" $((fib_value ^ fib_mask))
}

write_be16_journal()
{
	w16_image=$1
	w16_logical=$2
	w16_within=$3
	w16_value=$4
	w16_b0=$(((w16_value >> 8) & 255))
	w16_b1=$((w16_value & 255))
	journal_block "$w16_image" "$w16_logical"
	w16_offset=$((JOURNAL_BLOCK * CURRENT_BLOCK_SIZE + w16_within))
	write_byte "$w16_image" "$w16_offset" "$w16_b0"
	write_byte "$w16_image" $((w16_offset + 1)) "$w16_b1"
}

write_be32_journal()
{
	w32_image=$1
	w32_logical=$2
	w32_within=$3
	w32_value=$4
	w32_b0=$(((w32_value >> 24) & 255))
	w32_b1=$(((w32_value >> 16) & 255))
	w32_b2=$(((w32_value >> 8) & 255))
	w32_b3=$((w32_value & 255))
	journal_block "$w32_image" "$w32_logical"
	w32_offset=$((JOURNAL_BLOCK * CURRENT_BLOCK_SIZE + w32_within))
	write_byte "$w32_image" "$w32_offset" "$w32_b0"
	write_byte "$w32_image" $((w32_offset + 1)) "$w32_b1"
	write_byte "$w32_image" $((w32_offset + 2)) "$w32_b2"
	write_byte "$w32_image" $((w32_offset + 3)) "$w32_b3"
}

flip_journal_byte()
{
	image=$1
	logical=$2
	within=$3
	mask=$4
	journal_block "$image" "$logical"
	offset=$((JOURNAL_BLOCK * CURRENT_BLOCK_SIZE + within))
	value=$(dd if="$image" bs=1 skip="$offset" count=1 status=none |
	    od -An -tu1 | awk 'NF { printf "%d\n", $1 + 0 }')
	case "$value" in
	*[!0-9]*|'') fail "could not read journal byte" ;;
	esac
	write_byte "$image" "$offset" $((value ^ mask))
}

copy_journal_block()
{
	image=$1
	logical=$2
	output=$3
	journal_block "$image" "$logical"
	dd if="$image" of="$output" bs="$CURRENT_BLOCK_SIZE" \
	    skip="$JOURNAL_BLOCK" count=1 status=none
}

replace_journal_block()
{
	image=$1
	logical=$2
	input=$3
	journal_block "$image" "$logical"
	dd if="$input" of="$image" bs="$CURRENT_BLOCK_SIZE" \
	    seek="$JOURNAL_BLOCK" count=1 conv=notrunc status=none
}

expect_replay_failure_unchanged()
{
	image=$1
	before=$(sha256 -q "$image")
	run_fsck -fy "$image" "$case_dir/fsck.log"
	if [ "$FSCK_STATUS" -eq 0 ]; then
		fail "fsck_ext4fs accepted a malformed journal"
	fi
	[ "$FSCK_STATUS" -eq 8 ] ||
	    fail "malformed journal returned status $FSCK_STATUS, expected 8"
	after=$(sha256 -q "$image")
	[ "$before" = "$after" ] || fail "failed replay modified the image"
	grep -q 'JOURNAL REPLAY FAILED' "$case_dir/fsck.log" ||
	    fail "missing journal failure diagnostic"
}

test_basic_replay()
{
	format=$1
	open_command=$2
	case_dir=$work/$format
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 X
	{
		printf '%s\n' "$open_command"
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_nocsum()
{
	test_basic_replay nocsum journal_open
}

test_csum_v2()
{
	test_basic_replay csum-v2 'journal_open -c -v 2'
}

test_csum_v2_multiple_tags()
{
	case_dir=$work/csum-v2-multiple-tags
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 3
	make_random_payload "$case_dir/payload" 4096 3
	{
		printf 'journal_open -c -v 2\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	tags=$("$DEBUGFS" -R 'logdump -a' "$case_dir/image" 2>&1 |
	    grep -c 'FS block')
	[ "$tags" -eq 3 ] || fail "fixture does not contain three tags"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 3 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_csum_v3()
{
	test_basic_replay csum-v3 'journal_open -c -v 3'
}

test_escape()
{
	case_dir=$work/escape
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	printf '\300\073\071\230' >"$case_dir/payload"
	dd if=/dev/zero bs=4092 count=1 status=none | tr '\000' E \
	    >>"$case_dir/payload"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_revoke()
{
	case_dir=$work/revoke
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 R
	dd if=/dev/zero of="$case_dir/zero" bs=4096 count=1 status=none
	: >"$case_dir/empty"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_write -r %s %s\n' "$FREE_RANGE" \
		    "$case_dir/empty"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	if [ "$JOURNAL_TEST_MODE" = all ]; then
		grep -q 'journal revoke: 1 blocks revoked' "$case_dir/fsck.log" ||
		    fail "revoke record was not processed"
	fi
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/zero"
	verify_e2fsck "$case_dir/image"
}

test_multi_descriptor()
{
	case_dir=$work/multi-descriptor
	mkdir "$case_dir"
	create_image "$case_dir/image" 1024
	find_free_blocks "$case_dir/image" 130
	make_payload "$case_dir/payload" 1024 130 M
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	descriptors=$("$DEBUGFS" -R logdump "$case_dir/image" 2>&1 |
	    grep -c 'type 1 (descriptor block)')
	[ "$descriptors" -ge 3 ] || fail "fixture has fewer than 3 descriptors"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 1024 "$FREE_FIRST" 130 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_read_only()
{
	case_dir=$work/read-only
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 N
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	before=$(sha256 -q "$case_dir/image")
	run_fsck -fn "$case_dir/image" "$case_dir/fsck.log"
	if [ "$FSCK_STATUS" -eq 0 ]; then
		fail "read-only fsck accepted a journal that requires replay"
	fi
	[ "$FSCK_STATUS" -eq 8 ] ||
	    fail "read-only replay returned status $FSCK_STATUS, expected 8"
	after=$(sha256 -q "$case_dir/image")
	[ "$before" = "$after" ] || fail "read-only validation modified image"
	grep -q 'journal validates but must be replayed with write access' \
	    "$case_dir/fsck.log" || fail "missing read-only replay diagnostic"
}

test_clean_journal_recovery()
{
	case_dir=$work/clean-journal-recovery
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 Z
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"

	# Model a crash after home-block replay and the durable s_start=0 write,
	# but before the filesystem superblock's RECOVER bit was cleared.
	dd if="$case_dir/payload" of="$case_dir/image" bs=4096 \
	    seek="$FREE_FIRST" count=1 conv=notrunc status=none
	write_be32_journal "$case_dir/image" 0 28 0
	feature_offset=$((1024 + 96))
	read_le32_image "$case_dir/image" "$feature_offset"
	[ $((IMAGE_WORD & 4)) -ne 0 ] ||
	    fail "clean-journal fixture does not have RECOVER set"

	if [ "$JOURNAL_TEST_MODE" = all ]; then
		before=$(sha256 -q "$case_dir/image")
		run_fsck -fn "$case_dir/image" "$case_dir/fsck-readonly.log"
		[ "$FSCK_STATUS" -eq 8 ] ||
		    fail "read-only clean-journal recovery returned $FSCK_STATUS"
		after=$(sha256 -q "$case_dir/image")
		[ "$before" = "$after" ] ||
		    fail "read-only clean-journal recovery modified the image"
		grep -q 'RECOVER must be cleared with write access' \
		    "$case_dir/fsck-readonly.log" ||
		    fail "missing clean-journal read-only diagnostic"
	fi

	replay "$case_dir/image"
	read_be32_journal "$case_dir/image" 0 28
	[ "$JOURNAL_WORD" -eq 0 ] || fail "clean journal was made non-empty"
	read_le32_image "$case_dir/image" "$feature_offset"
	[ $((IMAGE_WORD & 4)) -eq 0 ] || fail "RECOVER was not cleared"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_bad_data_checksum()
{
	case_dir=$work/bad-data-checksum
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 X
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	flip_journal_byte "$case_dir/image" 2 0 1
	expect_replay_failure_unchanged "$case_dir/image"
}

test_incomplete_transaction()
{
	case_dir=$work/incomplete
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 I
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	journal_block "$case_dir/image" 3
	dd if=/dev/zero of="$case_dir/image" bs=4096 \
	    seek="$JOURNAL_BLOCK" count=1 conv=notrunc status=none
	expect_replay_failure_unchanged "$case_dir/image"
}

test_validation_atomicity()
{
	case_dir=$work/validation-atomicity
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 2
	set -- $FREE_BLOCKS
	first=$1
	second=$2
	make_payload "$case_dir/first" 4096 1 A
	make_payload "$case_dir/second" 4096 1 B
	dd if=/dev/zero of="$case_dir/zero" bs=4096 count=2 status=none
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$first" "$case_dir/first"
		printf 'journal_write -b %s %s\n' "$second" "$case_dir/second"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	flip_journal_byte "$case_dir/image" 5 0 1
	expect_replay_failure_unchanged "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$first" 2 "$case_dir/zero"
}

test_block_sizes()
{
	root_dir=$work/block-sizes
	mkdir "$root_dir"
	for size in 1024 2048 4096; do
		case_dir=$root_dir/$size
		mkdir "$case_dir"
		create_image "$case_dir/image" "$size"
		find_free_blocks "$case_dir/image" 1
		make_payload "$case_dir/payload" "$size" 1 B
		{
			printf 'journal_open -c -v 3\n'
			printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
			    "$case_dir/payload"
			printf 'journal_close\n'
		} >"$case_dir/debugfs.cmd"
		run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
		replay "$case_dir/image"
		compare_blocks "$case_dir/image" "$size" "$FREE_FIRST" 1 \
		    "$case_dir/payload"
		verify_e2fsck "$case_dir/image"
	done
}

test_descriptor_boundary()
{
	root_dir=$work/descriptor-boundary
	mkdir "$root_dir"
	for count in 62 63; do
		case_dir=$root_dir/$count
		mkdir "$case_dir"
		create_image "$case_dir/image" 1024
		find_free_blocks "$case_dir/image" "$count"
		make_payload "$case_dir/payload" 1024 "$count" D
		{
			printf 'journal_open -c -v 3\n'
			printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
			    "$case_dir/payload"
			printf 'journal_close\n'
		} >"$case_dir/debugfs.cmd"
		run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
		descriptors=$("$DEBUGFS" -R logdump "$case_dir/image" 2>&1 |
		    grep -c 'type 1 (descriptor block)')
		if [ "$count" -eq 62 ]; then
			[ "$descriptors" -eq 1 ] ||
			    fail "62 tags did not fit in one descriptor"
		else
			[ "$descriptors" -eq 2 ] ||
			    fail "63 tags did not split into two descriptors"
		fi
		replay "$case_dir/image"
		compare_blocks "$case_dir/image" 1024 "$FREE_FIRST" "$count" \
		    "$case_dir/payload"
		verify_e2fsck "$case_dir/image"
	done
}

test_revoke_then_later_write()
{
	case_dir=$work/revoke-later-write
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/old" 4096 1 O
	make_payload "$case_dir/new" 4096 1 L
	: >"$case_dir/empty"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" "$case_dir/old"
		printf 'journal_write -r %s %s\n' "$FREE_FIRST" "$case_dir/empty"
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" "$case_dir/new"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 "$case_dir/new"
	verify_e2fsck "$case_dir/image"
}

test_deleted_tag()
{
	case_dir=$work/deleted-tag
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 T
	dd if=/dev/zero of="$case_dir/zero" bs=4096 count=1 status=none
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	copy_journal_block "$case_dir/image" 3 "$case_dir/commit"
	replace_journal_block "$case_dir/image" 2 "$case_dir/commit"
	write_be16_journal "$case_dir/image" 1 18 12
	replay "$case_dir/image"
	if [ "$JOURNAL_TEST_MODE" = all ]; then
		grep -q 'journal replay: 0 blocks replayed' "$case_dir/fsck.log" ||
		    fail "deleted tag unexpectedly replayed a data block"
	fi
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 "$case_dir/zero"
	verify_e2fsck "$case_dir/image"
}

test_log_wraparound()
{
	case_dir=$work/log-wraparound
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 2
	set -- $FREE_BLOCKS
	first_target=$1
	second_target=$2
	make_payload "$case_dir/first" 4096 1 W
	make_payload "$case_dir/second" 4096 1 P
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$first_target" "$case_dir/first"
		printf 'journal_write -b %s %s\n' "$second_target" "$case_dir/second"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	for logical in 1 2 3 4 5 6; do
		copy_journal_block "$case_dir/image" "$logical" \
		    "$case_dir/journal.$logical"
	done
	read_be32_journal "$case_dir/image" 0 16
	maxlen=$JOURNAL_WORD
	read_be32_journal "$case_dir/image" 0 20
	journal_first=$JOURNAL_WORD
	wrap_start=$((maxlen - 3))
	replace_journal_block "$case_dir/image" "$wrap_start" \
	    "$case_dir/journal.1"
	replace_journal_block "$case_dir/image" $((wrap_start + 1)) \
	    "$case_dir/journal.2"
	replace_journal_block "$case_dir/image" $((wrap_start + 2)) \
	    "$case_dir/journal.3"
	replace_journal_block "$case_dir/image" "$journal_first" \
	    "$case_dir/journal.4"
	replace_journal_block "$case_dir/image" $((journal_first + 1)) \
	    "$case_dir/journal.5"
	replace_journal_block "$case_dir/image" $((journal_first + 2)) \
	    "$case_dir/journal.6"
	write_be32_journal "$case_dir/image" 0 28 "$wrap_start"
	replay "$case_dir/image"
	if [ "$JOURNAL_TEST_MODE" = all ]; then
		grep -q "journal scan: start block $wrap_start" \
		    "$case_dir/fsck.log" ||
		    fail "journal did not start at wrap boundary"
	fi
	compare_blocks "$case_dir/image" 4096 "$first_target" 1 \
	    "$case_dir/first"
	compare_blocks "$case_dir/image" 4096 "$second_target" 1 \
	    "$case_dir/second"
	verify_e2fsck "$case_dir/image"
}

test_sequence_wraparound()
{
	case_dir=$work/sequence-wraparound
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 2
	set -- $FREE_BLOCKS
	first_target=$1
	second_target=$2
	make_payload "$case_dir/first" 4096 1 S
	make_payload "$case_dir/second" 4096 1 Q
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$first_target" "$case_dir/first"
		printf 'journal_write -b %s %s\n' "$second_target" "$case_dir/second"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	write_be32_journal "$case_dir/image" 0 24 4294967295
	write_be32_journal "$case_dir/image" 1 8 4294967295
	write_be32_journal "$case_dir/image" 3 8 4294967295
	write_be32_journal "$case_dir/image" 4 8 0
	write_be32_journal "$case_dir/image" 6 8 0
	replay "$case_dir/image"
	if [ "$JOURNAL_TEST_MODE" = all ]; then
		grep -q 'end sequence 1 (2 transactions)' "$case_dir/fsck.log" ||
		    fail "transaction sequence did not wrap through zero"
	fi
	compare_blocks "$case_dir/image" 4096 "$first_target" 1 \
	    "$case_dir/first"
	compare_blocks "$case_dir/image" 4096 "$second_target" 1 \
	    "$case_dir/second"
	verify_e2fsck "$case_dir/image"
}

test_malformed_tags()
{
	root_dir=$work/malformed-tags
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 G
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	journal_block "$base_image" 2
	self_target=$JOURNAL_BLOCK

	for mutation in out-of-range unknown-flags missing-last self-target \
	    sequence-mismatch; do
		case_dir=$root_dir/$mutation
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		case "$mutation" in
		out-of-range)	write_be32_journal "$case_dir/image" 1 12 4294967295 ;;
		unknown-flags)	write_be16_journal "$case_dir/image" 1 18 32768 ;;
		missing-last)	write_be16_journal "$case_dir/image" 1 18 0 ;;
		self-target)	write_be32_journal "$case_dir/image" 1 12 "$self_target" ;;
		sequence-mismatch) write_be32_journal "$case_dir/image" 3 8 2 ;;
		esac
		expect_replay_failure_unchanged "$case_dir/image"
	done
}

test_checksum_failures()
{
	root_dir=$work/checksum-failures
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 C
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	for mutation in superblock descriptor data commit; do
		case_dir=$root_dir/$mutation
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		case "$mutation" in
		superblock)	flip_journal_byte "$case_dir/image" 0 100 1 ;;
		descriptor)	flip_journal_byte "$case_dir/image" 1 100 1 ;;
		data)		flip_journal_byte "$case_dir/image" 2 100 1 ;;
		commit)	flip_journal_byte "$case_dir/image" 3 100 1 ;;
		esac
		expect_replay_failure_unchanged "$case_dir/image"
	done

	case_dir=$root_dir/revoke-base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	: >"$case_dir/empty"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -r %s %s\n' "$FREE_FIRST" "$case_dir/empty"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	case_dir=$root_dir/revoke
	mkdir "$case_dir"
	cp "$base_image" "$case_dir/image"
	flip_journal_byte "$case_dir/image" 1 16 1
	expect_replay_failure_unchanged "$case_dir/image"
}

test_malformed_revoke_lengths()
{
	root_dir=$work/revoke-lengths
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	: >"$case_dir/empty"
	{
		printf 'journal_open\n'
		printf 'journal_write -r %s %s\n' "$FREE_FIRST" "$case_dir/empty"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	for length in 15 17 4294967295; do
		case_dir=$root_dir/$length
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		write_be32_journal "$case_dir/image" 1 12 "$length"
		expect_replay_failure_unchanged "$case_dir/image"
	done
}

test_malformed_geometry()
{
	root_dir=$work/malformed-geometry
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 Y
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	read_be32_journal "$base_image" 0 16
	maxlen=$JOURNAL_WORD
	for mutation in block-size maxlen first start unsupported-feature uuid; do
		case_dir=$root_dir/$mutation
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		case "$mutation" in
		block-size)	write_be32_journal "$case_dir/image" 0 12 1024 ;;
		maxlen)	write_be32_journal "$case_dir/image" 0 16 4294967295 ;;
		first)		write_be32_journal "$case_dir/image" 0 20 0 ;;
		start)		write_be32_journal "$case_dir/image" 0 28 "$maxlen" ;;
		unsupported-feature)
			write_be32_journal "$case_dir/image" 0 40 2147483650
			;;
		uuid)		flip_journal_byte "$case_dir/image" 0 48 1 ;;
		esac
		expect_replay_failure_unchanged "$case_dir/image"
	done
}

fuzz_reject_word()
{
	fr_base=$1
	fr_root=$2
	fr_name=$3
	fr_logical=$4
	fr_width=$5
	fr_offset=$6
	fr_value=$7

	case_dir=$fr_root/$fr_name
	mkdir "$case_dir"
	cp "$fr_base" "$case_dir/image"
	printf 'logical=%s width=%s offset=%s value=%s\n' \
	    "$fr_logical" "$fr_width" "$fr_offset" "$fr_value" \
	    >"$case_dir/mutation"
	case "$fr_width" in
	16)	write_be16_journal "$case_dir/image" "$fr_logical" \
		    "$fr_offset" "$fr_value" ;;
	32)	write_be32_journal "$case_dir/image" "$fr_logical" \
		    "$fr_offset" "$fr_value" ;;
	*)	fail "unsupported fuzz word width $fr_width" ;;
	esac
	expect_replay_failure_unchanged "$case_dir/image"
}

test_structured_field_fuzz()
{
	root_dir=$work/structured-field-fuzz
	mkdir "$root_dir"

	# A multi-tag, no-checksum descriptor reaches tag parsing directly.
	case_dir=$root_dir/descriptor-base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 8
	descriptor_target=$FREE_FIRST
	make_random_payload "$case_dir/payload" 4096 8
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	descriptor_base=$case_dir/image

	read_be32_journal "$descriptor_base" 0 40
	if [ $((JOURNAL_WORD & 2)) -ne 0 ]; then
		descriptor_tag_size=12
	else
		descriptor_tag_size=8
	fi
	tag_final_start=$((28 + 7 * descriptor_tag_size))
	tag_final_flags=$((tag_final_start + 6))
	tag_extra_start=$((tag_final_start + descriptor_tag_size))
	tag_extra_flags=$((tag_extra_start + 6))

	# The descriptor is block 1, its eight data blocks are 2..9, and the
	# commit is block 10.  The first v2 tag is followed by a 16-byte UUID;
	# derive later offsets from the journal's 32/64-bit tag format.
	while read name logical width offset value; do
		fuzz_reject_word "$descriptor_base" "$root_dir" "$name" \
		    "$logical" "$width" "$offset" "$value"
	done <<-EOF
	descriptor-type-zero 1 32 4 0
	descriptor-type-max 1 32 4 4294967295
	commit-magic-zero 10 32 0 0
	commit-type-descriptor 10 32 4 1
	commit-type-max 10 32 4 4294967295
	commit-sequence-zero 10 32 8 0
	tag-target-max 1 32 12 4294967295
	tag-first-same-uuid 1 16 18 10
	tag-count-too-small 1 16 18 8
	tag-missing-last 1 16 $tag_final_flags 2
	tag-unknown-flags 1 16 $tag_final_flags 32770
	EOF

	# Add a ninth synthetic tag after clearing LAST_TAG on tag eight.  Scan
	# must reject the derived over-count rather than consume the commit block
	# as journal data.
	case_dir=$root_dir/tag-count-too-large
	mkdir "$case_dir"
	cp "$descriptor_base" "$case_dir/image"
	write_be16_journal "$case_dir/image" 1 "$tag_final_flags" 2
	write_be32_journal "$case_dir/image" 1 "$tag_extra_start" \
	    "$descriptor_target"
	write_be16_journal "$case_dir/image" 1 "$tag_extra_flags" 10
	expect_replay_failure_unchanged "$case_dir/image"

	# Revoke lengths are byte counts including the 16-byte header.  These
	# boundary values are invalid for both four- and eight-byte records.
	case_dir=$root_dir/revoke-base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	: >"$case_dir/empty"
	{
		printf 'journal_open\n'
		printf 'journal_write -r %s %s\n' "$FREE_FIRST" \
		    "$case_dir/empty"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	revoke_base=$case_dir/image
	for length in 0 1 12 15 17 18 19 21 22 23 25 4095 4097 4294967295; do
		fuzz_reject_word "$revoke_base" "$root_dir" \
		    "revoke-length-$length" 1 32 12 "$length"
	done
	fuzz_reject_word "$revoke_base" "$root_dir" revoke-type-zero \
	    1 32 4 0
	fuzz_reject_word "$revoke_base" "$root_dir" revoke-type-max \
	    1 32 4 4294967295

	# Exercise superblock geometry and feature boundaries without checksums,
	# so rejection is attributable to field validation rather than CRC.
	read_be32_journal "$descriptor_base" 0 16
	journal_maxlen=$JOURNAL_WORD
	while read name offset value; do
		fuzz_reject_word "$descriptor_base" "$root_dir" "$name" \
		    0 32 "$offset" "$value"
	done <<-EOF
	super-magic-zero 0 0
	super-type-v1 4 3
	geometry-blocksize-zero 12 0
	geometry-blocksize-small 12 1024
	geometry-blocksize-large 12 8192
	geometry-maxlen-zero 16 0
	geometry-maxlen-one 16 1
	geometry-maxlen-max 16 4294967295
	geometry-first-zero 20 0
	geometry-first-at-end 20 $journal_maxlen
geometry-start-at-end 28 $journal_maxlen
	geometry-start-max 28 4294967295
	journal-errno-one 32 1
	feature-compat-unknown 36 1
	feature-incompat-unknown 40 2147483648
	feature-csum-v2-v3 40 24
	feature-ro-compat-unknown 44 1
	journal-users-zero 64 0
	journal-users-two 64 2
	EOF
}

test_randomized_replay()
{
	root_dir=$work/randomized-replay
	mkdir "$root_dir"
	iteration=0
	while [ "$iteration" -lt "$RANDOM_CASES" ]; do
		case_dir=$root_dir/$iteration
		mkdir "$case_dir"
		random_number
		case $((RANDOM_VALUE % 3)) in
		0) block_size=1024 ;;
		1) block_size=2048 ;;
		2) block_size=4096 ;;
		esac
		random_number
		case $((RANDOM_VALUE % 3)) in
		0) open_command=journal_open ;;
		1) open_command='journal_open -c -v 2' ;;
		2) open_command='journal_open -c -v 3' ;;
		esac
		random_number
		count=$((1 + RANDOM_VALUE % 16))
		random_number
		gap=$((RANDOM_VALUE % 16))
		create_image "$case_dir/image" "$block_size"
		find_free_blocks "$case_dir/image" $((count + gap))
		target=$((FREE_FIRST + gap))
		last=$((target + count - 1))
		if [ "$count" -eq 1 ]; then
			range=$target
		else
			range=$target-$last
		fi
		make_random_payload "$case_dir/payload" "$block_size" "$count"
		printf 'seed=%s block_size=%s format=%s count=%s target=%s\n' \
		    "$JOURNAL_SEED" "$block_size" "$open_command" "$count" \
		    "$range" >"$case_dir/parameters"
		{
			printf '%s\n' "$open_command"
			printf 'journal_write -b %s %s\n' "$range" "$case_dir/payload"
			printf 'journal_close\n'
		} >"$case_dir/debugfs.cmd"
		run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
		replay "$case_dir/image"
		compare_blocks "$case_dir/image" "$block_size" "$target" "$count" \
		    "$case_dir/payload"
		verify_e2fsck "$case_dir/image"
		iteration=$((iteration + 1))
	done
}

test_randomized_mutations()
{
	root_dir=$work/randomized-mutations
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 8
	make_random_payload "$case_dir/payload" 4096 8
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	iteration=0
	while [ "$iteration" -lt "$MUTATION_CASES" ]; do
		case_dir=$root_dir/$iteration
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		case $((iteration % 3)) in
		0) logical=1 ;;
		1) logical=10 ;;
		2) random_number; logical=$((2 + RANDOM_VALUE % 8)) ;;
		esac
		random_number
		case "$logical" in
		1|10)	within=$((12 + RANDOM_VALUE % (4096 - 12))) ;;
		*)	within=$((RANDOM_VALUE % 4096)) ;;
		esac
		random_number
		mask=$((1 << (RANDOM_VALUE % 8)))
		printf 'seed=%s logical=%s offset=%s mask=%s\n' "$JOURNAL_SEED" \
		    "$logical" "$within" "$mask" >"$case_dir/parameters"
		flip_journal_byte "$case_dir/image" "$logical" "$within" "$mask"
		expect_replay_failure_unchanged "$case_dir/image"
		iteration=$((iteration + 1))
	done
}

kernel_vnd_attach()
{
	kva_image=$1
	if ! kva_output=$(run_privileged "$VNCONFIG" "$kva_image"); then
		fail "could not attach vnode disk"
	fi
	set -- $kva_output
	KERNEL_VND=${1:-}
	case "$KERNEL_VND" in
	vnd[0-9]*) ;;
	*)	fail "vnconfig returned an invalid device: $kva_output" ;;
	esac
}

kernel_vnd_detach()
{
	if [ "$KERNEL_MOUNTED" -eq 1 ]; then
		run_privileged "$UMOUNT" "$KERNEL_MOUNTPOINT" ||
		    fail "could not unmount $KERNEL_MOUNTPOINT"
		KERNEL_MOUNTED=0
	fi
	if [ -n "$KERNEL_VND" ]; then
		run_privileged "$VNCONFIG" -u "$KERNEL_VND" ||
		    fail "could not detach $KERNEL_VND"
		KERNEL_VND=
	fi
}

kernel_mount_image()
{
	km_image=$1
	KERNEL_MOUNTPOINT=$case_dir/mnt
	mkdir -p "$KERNEL_MOUNTPOINT"
	kernel_vnd_attach "$km_image"
	km_device=/dev/${KERNEL_VND}c
	if ! run_privileged "$MOUNT_EXT4FS" "$km_device" \
	    "$KERNEL_MOUNTPOINT" >"$case_dir/kernel-mount.log" 2>&1; then
		cat "$case_dir/kernel-mount.log" >&2
		kernel_vnd_detach
		fail "kernel rejected a valid mount fixture"
	fi
	KERNEL_MOUNTED=1
	kernel_vnd_detach
}

kernel_replay()
{
	kr_image=$1
	kr_feature_offset=$((1024 + 96))
	read_le32_image "$kr_image" "$kr_feature_offset"
	[ $((IMAGE_WORD & 4)) -ne 0 ] ||
	    fail "kernel fixture does not have RECOVER set"

	kernel_mount_image "$kr_image"

	read_le32_image "$kr_image" "$kr_feature_offset"
	[ $((IMAGE_WORD & 4)) -eq 0 ] ||
	    fail "kernel replay did not clear RECOVER"
}

kernel_expect_mount_failure_unchanged()
{
	kf_image=$1
	before=$(sha256 -q "$kf_image")
	KERNEL_MOUNTPOINT=$case_dir/mnt
	mkdir -p "$KERNEL_MOUNTPOINT"
	kernel_vnd_attach "$kf_image"
	kf_device=/dev/${KERNEL_VND}c
	if run_privileged "$MOUNT_EXT4FS" "$kf_device" \
	    "$KERNEL_MOUNTPOINT" >"$case_dir/kernel-mount.log" 2>&1; then
		KERNEL_MOUNTED=1
		fail "kernel mounted a corrupt orphan fixture"
	fi
	kernel_vnd_detach
	after=$(sha256 -q "$kf_image")
	[ "$before" = "$after" ] ||
	    fail "failed orphan recovery modified the image"
}

test_classic_orphan_recovery()
{
	case_dir=$work/classic-orphan-recovery
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	make_payload "$case_dir/kept-payload" 4096 3 T
	make_payload "$case_dir/deleted-payload" 4096 2 D
	dd if=/dev/zero bs=1000 count=1 status=none | tr '\000' X \
	    >"$case_dir/xattr-value"
	{
		printf 'write %s /kept\n' "$case_dir/kept-payload"
		printf 'write %s /deleted\n' "$case_dir/deleted-payload"
		printf 'ea_set -f %s /deleted user.large\n' \
		    "$case_dir/xattr-value"
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	kept_ino=$("$DEBUGFS" -R 'stat /kept' "$case_dir/image" \
	    2>/dev/null | awk '/^Inode:/ { print $2; exit }')
	deleted_ino=$("$DEBUGFS" -R 'stat /deleted' "$case_dir/image" \
	    2>/dev/null | awk '/^Inode:/ { print $2; exit }')
	deleted_xattr=$("$DEBUGFS" -R 'stat /deleted' "$case_dir/image" \
	    2>/dev/null | awk '/^File ACL:/ { print $3; exit }')
	case "$kept_ino:$deleted_ino" in
	*[!0-9:]*) fail "could not resolve classic orphan inodes" ;;
	esac
	case "$deleted_xattr" in
	''|*[!0-9]*|0) fail "classic orphan fixture lacks an external xattr" ;;
	esac
	{
		printf 'unlink /deleted\n'
		printf 'set_inode_field <%s> links_count 0\n' "$deleted_ino"
		printf 'set_inode_field <%s> dtime 0\n' "$deleted_ino"
		printf 'set_inode_field <%s> size 4096\n' "$kept_ino"
		printf 'set_inode_field <%s> dtime %s\n' \
		    "$kept_ino" "$deleted_ino"
		printf 'set_super_value last_orphan %s\n' "$kept_ino"
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	"$DEBUGFS" -R orphan_inodes "$case_dir/image" 2>&1 |
	    grep -q "ino $deleted_ino" ||
	    fail "classic orphan fixture does not contain its tail"

	kernel_mount_image "$case_dir/image"
	"$DEBUGFS" -R "testi <$deleted_ino>" "$case_dir/image" 2>&1 |
	    grep -q 'not in use' || fail "deleted classic orphan remains allocated"
	set -- $("$DEBUGFS" -R "blocks <$kept_ino>" "$case_dir/image" \
	    2>/dev/null)
	[ "$#" -eq 1 ] || fail "linked classic orphan was not truncated"
	dd if="$case_dir/kept-payload" of="$case_dir/expected" bs=4096 \
	    count=1 status=none
	if ! "$DEBUGFS" -R "dump /kept $case_dir/actual" \
	    "$case_dir/image" >/dev/null 2>&1; then
		fail "could not extract recovered linked orphan"
	fi
	cmp -s "$case_dir/expected" "$case_dir/actual" ||
	    fail "linked orphan data changed during truncation"
	"$DEBUGFS" -R orphan_inodes "$case_dir/image" 2>&1 |
	    grep -q 'Orphan inode list empty' ||
	    fail "classic orphan root was not cleared"
	verify_e2fsck "$case_dir/image"

	# A second mount proves the completed state is itself restartable.
	kernel_mount_image "$case_dir/image"
	verify_e2fsck "$case_dir/image"
}

make_orphan_file_fixture()
{
	off_image=$1
	off_payload=$2
	create_orphan_file_image "$off_image" 4096
	printf 'write %s /deleted\n' "$off_payload" \
	    >"$case_dir/debugfs.cmd"
	run_debugfs "$off_image" "$case_dir/debugfs.cmd"
	ORPHAN_TARGET=$("$DEBUGFS" -R 'stat /deleted' "$off_image" \
	    2>/dev/null | awk '/^Inode:/ { print $2; exit }')
	ORPHAN_FILE_INO=$("$DEBUGFS" -R stats "$off_image" 2>/dev/null |
	    awk '/Orphan file inode:/ { print $4; exit }')
	ORPHAN_FILE_BLOCK=$("$DEBUGFS" \
	    -R "bmap <$ORPHAN_FILE_INO> 0" "$off_image" 2>/dev/null |
	    awk 'NF { value = $NF } END { print value }')
	ORPHAN_FILE_SEED=$("$DEBUGFS" -R stats "$off_image" 2>/dev/null |
	    awk '/Checksum seed:/ { print $3; exit }')
	ORPHAN_FILE_GEN=$("$DEBUGFS" \
	    -R "stat <$ORPHAN_FILE_INO>" "$off_image" 2>/dev/null |
	    awk '/Generation:/ { print $2; exit }')
	case "$ORPHAN_TARGET:$ORPHAN_FILE_INO:$ORPHAN_FILE_BLOCK:"\
"$ORPHAN_FILE_GEN" in
	*[!0-9:]*) fail "could not resolve orphan-file geometry" ;;
	esac
	case "$ORPHAN_FILE_SEED" in
	0x[0-9a-fA-F]*) ;;
	*) fail "could not resolve orphan-file checksum seed" ;;
	esac
	{
		printf 'unlink /deleted\n'
		printf 'set_inode_field <%s> links_count 0\n' "$ORPHAN_TARGET"
		printf 'set_inode_field <%s> dtime 0\n' "$ORPHAN_TARGET"
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$off_image" "$case_dir/debugfs.cmd"
	if ! "$ORPHAN_FIXTURE" "$off_image" 4096 "$ORPHAN_FILE_BLOCK" \
	    "$ORPHAN_FILE_SEED" "$ORPHAN_FILE_INO" "$ORPHAN_FILE_GEN" \
	    "$ORPHAN_TARGET" >"$case_dir/orphan-fixture.log" 2>&1; then
		cat "$case_dir/orphan-fixture.log" >&2
		fail "could not populate orphan file"
	fi
	if ! "$DEBUGFS" -w -R 'feature orphan_present' "$off_image" \
	    >"$case_dir/orphan-feature.log" 2>&1; then
		cat "$case_dir/orphan-feature.log" >&2
		fail "could not set ORPHAN_PRESENT"
	fi
}

test_orphan_file_recovery()
{
	case_dir=$work/orphan-file-recovery
	mkdir "$case_dir"
	make_payload "$case_dir/payload" 4096 3 O
	make_orphan_file_fixture "$case_dir/image" "$case_dir/payload"
	"$DEBUGFS" -R orphan_inodes "$case_dir/image" 2>&1 |
	    grep -q "ino $ORPHAN_TARGET" ||
	    fail "orphan-file fixture does not contain its target"

	kernel_mount_image "$case_dir/image"
	"$DEBUGFS" -R "testi <$ORPHAN_TARGET>" "$case_dir/image" 2>&1 |
	    grep -q 'not in use' || fail "orphan-file target remains allocated"
	read_le32_image "$case_dir/image" $((1024 + 100))
	[ $((IMAGE_WORD & 65536)) -eq 0 ] ||
	    fail "ORPHAN_PRESENT was not cleared"
	verify_e2fsck "$case_dir/image"
	kernel_mount_image "$case_dir/image"
	verify_e2fsck "$case_dir/image"
}

test_corrupt_orphan_file()
{
	case_dir=$work/corrupt-orphan-file
	mkdir "$case_dir"
	make_payload "$case_dir/payload" 4096 1 C
	make_orphan_file_fixture "$case_dir/image" "$case_dir/payload"
	flip_image_byte "$case_dir/image" \
	    $((ORPHAN_FILE_BLOCK * 4096 + 4095)) 1
	read_le32_image "$case_dir/image" $((1024 + 100))
	[ $((IMAGE_WORD & 65536)) -ne 0 ] ||
	    fail "corrupt fixture does not have ORPHAN_PRESENT set"
	kernel_expect_mount_failure_unchanged "$case_dir/image"
	read_le32_image "$case_dir/image" $((1024 + 100))
	[ $((IMAGE_WORD & 65536)) -ne 0 ] ||
	    fail "failed orphan recovery cleared ORPHAN_PRESENT"
}

test_corrupt_classic_orphans()
{
	case_dir=$work/corrupt-classic-orphans
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	make_payload "$case_dir/first-payload" 4096 1 A
	make_payload "$case_dir/second-payload" 4096 1 B
	{
		printf 'write %s /first\n' "$case_dir/first-payload"
		printf 'write %s /second\n' "$case_dir/second-payload"
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	first_ino=$("$DEBUGFS" -R 'stat /first' "$case_dir/image" \
	    2>/dev/null | awk '/^Inode:/ { print $2; exit }')
	second_ino=$("$DEBUGFS" -R 'stat /second' "$case_dir/image" \
	    2>/dev/null | awk '/^Inode:/ { print $2; exit }')
	case "$first_ino:$second_ino" in
	*[!0-9:]*) fail "could not resolve corrupt classic orphan inodes" ;;
	esac
	{
		printf 'set_inode_field <%s> dtime %s\n' \
		    "$first_ino" "$second_ino"
		printf 'set_inode_field <%s> dtime %s\n' \
		    "$second_ino" "$first_ino"
		printf 'set_super_value last_orphan %s\n' "$first_ino"
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	kernel_expect_mount_failure_unchanged "$case_dir/image"
}

test_kernel_mount_corruption()
{
	root_dir=$work/kernel-mount-corruption
	case_dir=$root_dir/base
	mkdir -p "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 K
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	cp "$case_dir/image" "$root_dir/valid.img"
	cp "$case_dir/image" "$root_dir/corrupt.img"
	flip_journal_byte "$root_dir/corrupt.img" 2 100 1

	# ext4's s_feature_incompat is at byte 96 in the 1024-byte superblock.
	feature_offset=$((1024 + 96))
	read_le32_image "$root_dir/corrupt.img" "$feature_offset"
	[ $((IMAGE_WORD & 4)) -ne 0 ] ||
	    fail "corrupt fixture does not have RECOVER set"

	KERNEL_MOUNTPOINT=$root_dir/mnt
	mkdir "$KERNEL_MOUNTPOINT"

	# A valid twin must mount and replay first.  This proves the running
	# kernel, vnode disk, mount utility, and fixture all exercise ext4fs.
	kernel_vnd_attach "$root_dir/valid.img"
	valid_device=/dev/${KERNEL_VND}c
	if ! run_privileged "$MOUNT_EXT4FS" "$valid_device" \
	    "$KERNEL_MOUNTPOINT" >"$root_dir/valid-mount.log" 2>&1; then
		cat "$root_dir/valid-mount.log" >&2
		fail "kernel rejected the valid journal control"
	fi
	KERNEL_MOUNTED=1
	kernel_vnd_detach
	read_le32_image "$root_dir/valid.img" "$feature_offset"
	[ $((IMAGE_WORD & 4)) -eq 0 ] ||
	    fail "valid kernel replay did not clear RECOVER"
	case_dir=$root_dir
	compare_blocks "$root_dir/valid.img" 4096 "$FREE_FIRST" 1 \
	    "$root_dir/base/payload"
	verify_e2fsck "$root_dir/valid.img"

	# The corrupted twin must fail mount before making any disk change.
	before=$(sha256 -q "$root_dir/corrupt.img")
	kernel_vnd_attach "$root_dir/corrupt.img"
	corrupt_device=/dev/${KERNEL_VND}c
	if run_privileged "$MOUNT_EXT4FS" "$corrupt_device" \
	    "$KERNEL_MOUNTPOINT" >"$root_dir/corrupt-mount.log" 2>&1; then
		KERNEL_MOUNTED=1
		fail "kernel mounted an image with a corrupted journal"
	fi
	kernel_vnd_detach
	after=$(sha256 -q "$root_dir/corrupt.img")
	[ "$before" = "$after" ] ||
	    fail "failed kernel replay modified the image"
	read_le32_image "$root_dir/corrupt.img" "$feature_offset"
	[ $((IMAGE_WORD & 4)) -ne 0 ] ||
	    fail "failed kernel replay cleared RECOVER"
}

run_test()
{
	test_name=$1
	shift
	printf '%-44s' "$test_name"
	"$@"
	echo ' ok'
}

if [ "$JOURNAL_TEST_MODE" = all ]; then
	echo "random seed: $JOURNAL_SEED"
	run_test 'journal replay without checksums' test_nocsum
	run_test 'journal replay with checksum v2' test_csum_v2
	run_test 'checksum v2 descriptor with multiple tags' \
	    test_csum_v2_multiple_tags
	run_test 'journal replay with checksum v3' test_csum_v3
	run_test 'escaped journal data' test_escape
	run_test 'revoke suppresses an earlier write' test_revoke
	run_test 'later write survives an earlier revoke' test_revoke_then_later_write
	run_test 'deleted descriptor tag' test_deleted_tag
	run_test 'transaction spanning descriptor blocks' test_multi_descriptor
	run_test 'descriptor capacity boundary' test_descriptor_boundary
	run_test 'journal log block wraparound' test_log_wraparound
	run_test 'transaction ID wraparound' test_sequence_wraparound
	run_test 'read-only validation is non-mutating' test_read_only
	run_test 'restart clean journal with RECOVER set' \
	    test_clean_journal_recovery
	run_test 'bad data checksum is non-mutating' test_bad_data_checksum
	run_test 'incomplete transaction is non-mutating' test_incomplete_transaction
	run_test 'validation precedes every home write' test_validation_atomicity
	run_test '1K, 2K, and 4K filesystem blocks' test_block_sizes
	run_test 'malformed descriptor tags and sequences' test_malformed_tags
	run_test 'all journal checksum failure points' test_checksum_failures
	run_test 'malformed revoke lengths' test_malformed_revoke_lengths
	run_test 'malformed journal geometry and features' test_malformed_geometry
	run_test 'structured journal field fuzzing' test_structured_field_fuzz
	run_test 'seeded replay matrix' test_randomized_replay
	run_test 'seeded checksum mutation sweep' test_randomized_mutations
else
	run_test 'kernel: journal without checksums' test_nocsum
	run_test 'kernel: checksum v2' test_csum_v2
	run_test 'kernel: checksum v2 multiple tags' \
	    test_csum_v2_multiple_tags
	run_test 'kernel: checksum v3' test_csum_v3
	run_test 'kernel: escaped data' test_escape
	run_test 'kernel: revoke' test_revoke
	run_test 'kernel: later write after revoke' test_revoke_then_later_write
	run_test 'kernel: deleted tag' test_deleted_tag
	run_test 'kernel: multiple descriptors' test_multi_descriptor
	run_test 'kernel: descriptor boundary' test_descriptor_boundary
	run_test 'kernel: log wraparound' test_log_wraparound
	run_test 'kernel: sequence wraparound' test_sequence_wraparound
	run_test 'kernel: clean journal with RECOVER' \
	    test_clean_journal_recovery
	run_test 'kernel: filesystem block sizes' test_block_sizes
	run_test 'kernel: seeded replay matrix' test_randomized_replay
	run_test 'kernel: restartable classic orphan recovery' \
	    test_classic_orphan_recovery
	run_test 'kernel: restartable orphan-file recovery' \
	    test_orphan_file_recovery
	run_test 'kernel: corrupt orphan file is non-mutating' \
	    test_corrupt_orphan_file
	run_test 'kernel: classic orphan cycle is non-mutating' \
	    test_corrupt_classic_orphans
	run_test 'kernel mount preserves RECOVER on corruption' \
	    test_kernel_mount_corruption
fi
