#!/bin/sh
#
# Build fsck_ext4fs outside the source tree, create disposable ext4 images,
# and exercise JBD2 recovery generated by e2fsprogs debugfs.

set -eu

MKE2FS=${MKE2FS:-mke2fs}
DEBUGFS=${DEBUGFS:-debugfs}
E2FSCK=${E2FSCK:-e2fsck}
MAKE=${MAKE:-make}

for tool in "$MKE2FS" "$DEBUGFS" "$E2FSCK" sha256 dd tr cmp awk grep sed; do
	if ! command -v "$tool" >/dev/null 2>&1; then
		echo "SKIPPED: fsck_ext4fs journal regress requires $tool"
		exit 0
	fi
done

work=$(mktemp -d /tmp/fsck_ext4fs_journal.XXXXXXXX)
case "$work" in
/tmp/fsck_ext4fs_journal.*) ;;
*)	echo "unsafe temporary directory: $work" >&2
	exit 1
	;;
esac

cleanup()
{
	rc=$?
	trap - EXIT HUP INT TERM
	if [ "${KEEP_TMP:-0}" = 1 ]; then
		echo "temporary files retained in $work"
	else
		rm -rf "$work"
	fi
	exit "$rc"
}
trap cleanup EXIT HUP INT TERM

script_dir=$(CDPATH= cd "$(dirname "$0")" && pwd)
srcroot=$(CDPATH= cd "$script_dir/../../.." && pwd)

fail()
{
	echo "FAILED: $test_name: $*" >&2
	exit 1
}

if [ -z "${FSCK_EXT4FS:-}" ]; then
	objdir=$work/obj
	mkdir "$objdir"
	if ! MAKEOBJDIR="$objdir" "$MAKE" -s \
	    -C "$srcroot/sbin/fsck_ext4fs" >"$work/build.log" 2>&1; then
		cat "$work/build.log" >&2
		test_name=build
		fail "could not build fsck_ext4fs"
	fi
	FSCK_EXT4FS=$objdir/fsck_ext4fs
fi
if [ ! -x "$FSCK_EXT4FS" ]; then
	test_name=build
	fail "$FSCK_EXT4FS is not executable"
fi

create_image()
{
	image=$1
	block_size=$2
	dd if=/dev/zero of="$image" bs=1m count=64 status=none
	if ! "$MKE2FS" -q -F -t ext4 -b "$block_size" \
	    -O '^orphan_file' "$image" >"$case_dir/mke2fs.log" 2>&1; then
		cat "$case_dir/mke2fs.log" >&2
		fail "mke2fs failed"
	fi
}

make_payload()
{
	file=$1
	block_size=$2
	blocks=$3
	byte=$4
	dd if=/dev/zero bs="$block_size" count="$blocks" status=none |
	    tr '\000' "$byte" >"$file"
}

find_free_blocks()
{
	image=$1
	count=$2
	FREE_BLOCKS=$("$DEBUGFS" -R "find_free_block $count" "$image" \
	    2>/dev/null | sed -n 's/^Free blocks found:[[:space:]]*//p')
	set -- $FREE_BLOCKS
	[ "$#" -eq "$count" ] || fail "could not find $count free blocks"

	FREE_FIRST=$1
	FREE_LAST=$1
	expected=$1
	for block in "$@"; do
		case "$block" in
		*[!0-9]*|'') fail "debugfs returned a bad block number" ;;
		esac
		[ "$block" -eq "$expected" ] ||
		    fail "debugfs did not return consecutive free blocks"
		FREE_LAST=$block
		expected=$((expected + 1))
	done
	if [ "$count" -eq 1 ]; then
		FREE_RANGE=$FREE_FIRST
	else
		FREE_RANGE=$FREE_FIRST-$FREE_LAST
	fi
}

run_debugfs()
{
	image=$1
	commands=$2
	if ! "$DEBUGFS" -w -f "$commands" "$image" \
	    >"$case_dir/debugfs.log" 2>&1; then
		cat "$case_dir/debugfs.log" >&2
		fail "debugfs failed"
	fi
}

replay()
{
	image=$1
	if ! "$FSCK_EXT4FS" -fy "$image" >"$case_dir/fsck.log" 2>&1; then
		cat "$case_dir/fsck.log" >&2
		fail "fsck_ext4fs rejected a valid journal"
	fi
	grep -q 'journal replay complete' "$case_dir/fsck.log" ||
	    fail "fsck_ext4fs did not report completed replay"
}

verify_e2fsck()
{
	image=$1
	if ! "$E2FSCK" -fn "$image" >"$case_dir/e2fsck.log" 2>&1; then
		cat "$case_dir/e2fsck.log" >&2
		fail "e2fsck rejected the recovered image"
	fi
}

compare_blocks()
{
	image=$1
	block_size=$2
	first=$3
	count=$4
	expected=$5
	dd if="$image" bs="$block_size" skip="$first" count="$count" \
	    status=none | cmp -s - "$expected" ||
	    fail "replayed home block contents differ"
}

journal_block()
{
	image=$1
	logical=$2
	JOURNAL_BLOCK=$("$DEBUGFS" -R "bmap <8> $logical" "$image" \
	    2>/dev/null | awk 'NF { value = $NF } END { print value }')
	case "$JOURNAL_BLOCK" in
	*[!0-9]*|'') fail "could not map journal block $logical" ;;
	esac
}

expect_replay_failure_unchanged()
{
	image=$1
	before=$(sha256 -q "$image")
	if "$FSCK_EXT4FS" -fy "$image" >"$case_dir/fsck.log" 2>&1; then
		fail "fsck_ext4fs accepted a malformed journal"
	fi
	after=$(sha256 -q "$image")
	[ "$before" = "$after" ] || fail "failed replay modified the image"
	grep -q 'JOURNAL REPLAY FAILED' "$case_dir/fsck.log" ||
	    fail "missing journal failure diagnostic"
}

test_basic_replay()
{
	format=$1
	open_command=$2
	case_dir=$work/$format
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 X
	{
		printf '%s\n' "$open_command"
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_nocsum()
{
	test_basic_replay nocsum journal_open
}

test_csum_v2()
{
	test_basic_replay csum-v2 'journal_open -c -v 2'
}

test_csum_v3()
{
	test_basic_replay csum-v3 'journal_open -c -v 3'
}

test_escape()
{
	case_dir=$work/escape
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	printf '\300\073\071\230' >"$case_dir/payload"
	dd if=/dev/zero bs=4092 count=1 status=none | tr '\000' E \
	    >>"$case_dir/payload"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_revoke()
{
	case_dir=$work/revoke
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 R
	dd if=/dev/zero of="$case_dir/zero" bs=4096 count=1 status=none
	: >"$case_dir/empty"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_write -r %s %s\n' "$FREE_RANGE" \
		    "$case_dir/empty"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	grep -q 'journal revoke: 1 blocks revoked' "$case_dir/fsck.log" ||
	    fail "revoke record was not processed"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/zero"
	verify_e2fsck "$case_dir/image"
}

test_multi_descriptor()
{
	case_dir=$work/multi-descriptor
	mkdir "$case_dir"
	create_image "$case_dir/image" 1024
	find_free_blocks "$case_dir/image" 130
	make_payload "$case_dir/payload" 1024 130 M
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	descriptors=$("$DEBUGFS" -R logdump "$case_dir/image" 2>&1 |
	    grep -c 'type 1 (descriptor block)')
	[ "$descriptors" -ge 3 ] || fail "fixture has fewer than 3 descriptors"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 1024 "$FREE_FIRST" 130 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_read_only()
{
	case_dir=$work/read-only
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 N
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	before=$(sha256 -q "$case_dir/image")
	if "$FSCK_EXT4FS" -fn "$case_dir/image" >"$case_dir/fsck.log" 2>&1; then
		fail "read-only fsck accepted a journal that requires replay"
	fi
	after=$(sha256 -q "$case_dir/image")
	[ "$before" = "$after" ] || fail "read-only validation modified image"
	grep -q 'journal validates but must be replayed with write access' \
	    "$case_dir/fsck.log" || fail "missing read-only replay diagnostic"
}

test_bad_data_checksum()
{
	case_dir=$work/bad-data-checksum
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 X
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	journal_block "$case_dir/image" 2
	offset=$((JOURNAL_BLOCK * 4096))
	printf '\103' | dd of="$case_dir/image" bs=1 seek="$offset" count=1 \
	    conv=notrunc status=none
	expect_replay_failure_unchanged "$case_dir/image"
}

test_incomplete_transaction()
{
	case_dir=$work/incomplete
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 I
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	journal_block "$case_dir/image" 3
	dd if=/dev/zero of="$case_dir/image" bs=4096 skip=0 \
	    seek="$JOURNAL_BLOCK" count=1 conv=notrunc status=none
	expect_replay_failure_unchanged "$case_dir/image"
}

test_validation_atomicity()
{
	case_dir=$work/validation-atomicity
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 2
	set -- $FREE_BLOCKS
	first=$1
	second=$2
	make_payload "$case_dir/first" 4096 1 A
	make_payload "$case_dir/second" 4096 1 B
	dd if=/dev/zero of="$case_dir/zero" bs=4096 count=2 status=none
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$first" "$case_dir/first"
		printf 'journal_write -b %s %s\n' "$second" "$case_dir/second"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	journal_block "$case_dir/image" 5
	offset=$((JOURNAL_BLOCK * 4096))
	printf '\103' | dd of="$case_dir/image" bs=1 seek="$offset" count=1 \
	    conv=notrunc status=none
	expect_replay_failure_unchanged "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$first" 2 "$case_dir/zero"
}

run_test()
{
	test_name=$1
	shift
	printf '%-44s' "$test_name"
	"$@"
	echo ' ok'
}

run_test 'journal replay without checksums' test_nocsum
run_test 'journal replay with checksum v2' test_csum_v2
run_test 'journal replay with checksum v3' test_csum_v3
run_test 'escaped journal data' test_escape
run_test 'revoke suppresses an earlier write' test_revoke
run_test 'transaction spanning descriptor blocks' test_multi_descriptor
run_test 'read-only validation is non-mutating' test_read_only
run_test 'bad data checksum is non-mutating' test_bad_data_checksum
run_test 'incomplete transaction is non-mutating' test_incomplete_transaction
run_test 'validation precedes every home write' test_validation_atomicity
