#!/bin/sh
#
# Build fsck_ext4fs outside the source tree, create disposable ext4 images,
# and exercise JBD2 recovery generated by e2fsprogs debugfs.
#
# JOURNAL_SEED reproduces randomized choices.  RANDOM_CASES and
# MUTATION_CASES control the randomized workload, FSCK_TIMEOUT bounds each
# checker invocation, and KEEP_TMP=1 retains generated fixtures.

set -eu

MKE2FS=${MKE2FS:-mke2fs}
DEBUGFS=${DEBUGFS:-debugfs}
E2FSCK=${E2FSCK:-e2fsck}
MAKE=${MAKE:-make}
TIMEOUT=${TIMEOUT:-timeout}
FSCK_TIMEOUT=${FSCK_TIMEOUT:-20}
JOURNAL_SEED=${JOURNAL_SEED:-260921}
RANDOM_CASES=${RANDOM_CASES:-6}
MUTATION_CASES=${MUTATION_CASES:-18}

for tool in "$MKE2FS" "$DEBUGFS" "$E2FSCK" "$TIMEOUT" \
    sha256 dd tr cmp cp awk grep sed od; do
	if ! command -v "$tool" >/dev/null 2>&1; then
		echo "SKIPPED: fsck_ext4fs journal regress requires $tool"
		exit 0
	fi
done

case "$FSCK_TIMEOUT:$JOURNAL_SEED:$RANDOM_CASES:$MUTATION_CASES" in
*[!0-9:]*)	echo "timeout, seed, and case counts must be unsigned integers" >&2
	exit 1
	;;
esac
[ "$FSCK_TIMEOUT" -gt 0 ] || { echo "FSCK_TIMEOUT must be positive" >&2; exit 1; }
[ "$JOURNAL_SEED" -le 2147483647 ] || { echo "JOURNAL_SEED is too large" >&2; exit 1; }
[ "$RANDOM_CASES" -le 32 ] || { echo "RANDOM_CASES is too large" >&2; exit 1; }
[ "$MUTATION_CASES" -le 96 ] || { echo "MUTATION_CASES is too large" >&2; exit 1; }
RNG_STATE=$JOURNAL_SEED
ulimit -c 0

work=$(mktemp -d /tmp/fsck_ext4fs_journal.XXXXXXXX)
case "$work" in
/tmp/fsck_ext4fs_journal.*) ;;
*)	echo "unsafe temporary directory: $work" >&2
	exit 1
	;;
esac

cleanup()
{
	rc=$?
	trap - EXIT HUP INT TERM
	if [ "${KEEP_TMP:-0}" = 1 ] || [ "$rc" -ne 0 ]; then
		echo "temporary files retained in $work"
	else
		rm -rf "$work"
	fi
	exit "$rc"
}
trap cleanup EXIT HUP INT TERM

script_dir=$(CDPATH= cd "$(dirname "$0")" && pwd)
srcroot=$(CDPATH= cd "$script_dir/../../.." && pwd)

fail()
{
	echo "FAILED: $test_name: $*" >&2
	exit 1
}

random_number()
{
	RNG_STATE=$(((RNG_STATE * 1103515245 + 12345) & 2147483647))
	RANDOM_VALUE=$RNG_STATE
}

if [ -z "${FSCK_EXT4FS:-}" ]; then
	objdir=$work/obj
	mkdir "$objdir"
	if ! MAKEOBJDIR="$objdir" "$MAKE" -s \
	    -C "$srcroot/sbin/fsck_ext4fs" >"$work/build.log" 2>&1; then
		cat "$work/build.log" >&2
		test_name=build
		fail "could not build fsck_ext4fs"
	fi
	FSCK_EXT4FS=$objdir/fsck_ext4fs
fi
if [ ! -x "$FSCK_EXT4FS" ]; then
	test_name=build
	fail "$FSCK_EXT4FS is not executable"
fi

create_image()
{
	image=$1
	block_size=$2
	CURRENT_BLOCK_SIZE=$block_size
	dd if=/dev/zero of="$image" bs=1m count=0 seek=64 status=none
	if ! "$MKE2FS" -q -F -t ext4 -b "$block_size" \
	    -O '^orphan_file' "$image" >"$case_dir/mke2fs.log" 2>&1; then
		cat "$case_dir/mke2fs.log" >&2
		fail "mke2fs failed"
	fi
}

make_payload()
{
	file=$1
	block_size=$2
	blocks=$3
	byte=$4
	dd if=/dev/zero bs="$block_size" count="$blocks" status=none |
	    tr '\000' "$byte" >"$file"
}

make_random_payload()
{
	file=$1
	block_size=$2
	blocks=$3
	: >"$file"
	index=0
	while [ "$index" -lt "$blocks" ]; do
		random_number
		value=$((65 + RANDOM_VALUE % 26))
		octal=$(printf '%03o' "$value")
		byte=$(printf "\\$octal")
		dd if=/dev/zero bs="$block_size" count=1 status=none |
		    tr '\000' "$byte" >>"$file"
		index=$((index + 1))
	done
}

find_free_blocks()
{
	ff_image=$1
	ff_count=$2
	FREE_BLOCKS=$("$DEBUGFS" -R "find_free_block $ff_count" "$ff_image" \
	    2>/dev/null | sed -n 's/^Free blocks found:[[:space:]]*//p')
	set -- $FREE_BLOCKS
	[ "$#" -eq "$ff_count" ] || fail "could not find $ff_count free blocks"

	FREE_FIRST=$1
	FREE_LAST=$1
	expected=$1
	for block in "$@"; do
		case "$block" in
		*[!0-9]*|'') fail "debugfs returned a bad block number" ;;
		esac
		[ "$block" -eq "$expected" ] ||
		    fail "debugfs did not return consecutive free blocks"
		FREE_LAST=$block
		expected=$((expected + 1))
	done
	if [ "$ff_count" -eq 1 ]; then
		FREE_RANGE=$FREE_FIRST
	else
		FREE_RANGE=$FREE_FIRST-$FREE_LAST
	fi
}

run_debugfs()
{
	image=$1
	commands=$2
	if ! "$DEBUGFS" -w -f "$commands" "$image" \
	    >"$case_dir/debugfs.log" 2>&1; then
		cat "$case_dir/debugfs.log" >&2
		fail "debugfs failed"
	fi
}

run_fsck()
{
	mode=$1
	image=$2
	log=$3
	if "$TIMEOUT" -k 2 "$FSCK_TIMEOUT" "$FSCK_EXT4FS" "$mode" \
	    "$image" >"$log" 2>&1; then
		FSCK_STATUS=0
	else
		FSCK_STATUS=$?
	fi
	case "$FSCK_STATUS" in
	124|137)	fail "fsck_ext4fs exceeded ${FSCK_TIMEOUT}s timeout" ;;
	1[2-9][0-9]|[2-9][0-9][0-9])
		fail "fsck_ext4fs terminated abnormally (status $FSCK_STATUS)"
		;;
	esac
}

replay()
{
	image=$1
	run_fsck -fy "$image" "$case_dir/fsck.log"
	if [ "$FSCK_STATUS" -ne 0 ]; then
		cat "$case_dir/fsck.log" >&2
		fail "fsck_ext4fs rejected a valid journal (status $FSCK_STATUS)"
	fi
	grep -q 'journal replay complete' "$case_dir/fsck.log" ||
	    fail "fsck_ext4fs did not report completed replay"
}

verify_e2fsck()
{
	image=$1
	if ! "$E2FSCK" -fn "$image" >"$case_dir/e2fsck.log" 2>&1; then
		cat "$case_dir/e2fsck.log" >&2
		fail "e2fsck rejected the recovered image"
	fi
}

compare_blocks()
{
	image=$1
	block_size=$2
	first=$3
	count=$4
	expected=$5
	dd if="$image" bs="$block_size" skip="$first" count="$count" \
	    status=none | cmp -s - "$expected" ||
	    fail "replayed home block contents differ"
}

journal_block()
{
	jb_image=$1
	jb_logical=$2
	JOURNAL_BLOCK=$("$DEBUGFS" -R "bmap <8> $jb_logical" "$jb_image" \
	    2>/dev/null | awk 'NF { value = $NF } END { print value }')
	case "$JOURNAL_BLOCK" in
	*[!0-9]*|'') fail "could not map journal block $jb_logical" ;;
	esac
}

read_be32_journal()
{
	image=$1
	logical=$2
	within=$3
	journal_block "$image" "$logical"
	offset=$((JOURNAL_BLOCK * CURRENT_BLOCK_SIZE + within))
	set -- $(dd if="$image" bs=1 skip="$offset" count=4 status=none |
	    od -An -tu1)
	[ "$#" -eq 4 ] || fail "could not read journal word"
	JOURNAL_WORD=$((($1 << 24) | ($2 << 16) | ($3 << 8) | $4))
}

write_byte()
{
	byte_image=$1
	byte_offset=$2
	byte_value=$3
	[ "$byte_value" -ge 0 ] && [ "$byte_value" -le 255 ] ||
	    fail "byte value is out of range"
	byte_octal=$(printf '%03o' "$byte_value")
	printf "\\$byte_octal" | dd of="$byte_image" bs=1 seek="$byte_offset" count=1 \
	    conv=notrunc status=none
}

write_be16_journal()
{
	w16_image=$1
	w16_logical=$2
	w16_within=$3
	w16_value=$4
	w16_b0=$(((w16_value >> 8) & 255))
	w16_b1=$((w16_value & 255))
	journal_block "$w16_image" "$w16_logical"
	w16_offset=$((JOURNAL_BLOCK * CURRENT_BLOCK_SIZE + w16_within))
	write_byte "$w16_image" "$w16_offset" "$w16_b0"
	write_byte "$w16_image" $((w16_offset + 1)) "$w16_b1"
}

write_be32_journal()
{
	w32_image=$1
	w32_logical=$2
	w32_within=$3
	w32_value=$4
	w32_b0=$(((w32_value >> 24) & 255))
	w32_b1=$(((w32_value >> 16) & 255))
	w32_b2=$(((w32_value >> 8) & 255))
	w32_b3=$((w32_value & 255))
	journal_block "$w32_image" "$w32_logical"
	w32_offset=$((JOURNAL_BLOCK * CURRENT_BLOCK_SIZE + w32_within))
	write_byte "$w32_image" "$w32_offset" "$w32_b0"
	write_byte "$w32_image" $((w32_offset + 1)) "$w32_b1"
	write_byte "$w32_image" $((w32_offset + 2)) "$w32_b2"
	write_byte "$w32_image" $((w32_offset + 3)) "$w32_b3"
}

flip_journal_byte()
{
	image=$1
	logical=$2
	within=$3
	mask=$4
	journal_block "$image" "$logical"
	offset=$((JOURNAL_BLOCK * CURRENT_BLOCK_SIZE + within))
	value=$(dd if="$image" bs=1 skip="$offset" count=1 status=none |
	    od -An -tu1 | awk 'NF { printf "%d\n", $1 + 0 }')
	case "$value" in
	*[!0-9]*|'') fail "could not read journal byte" ;;
	esac
	write_byte "$image" "$offset" $((value ^ mask))
}

copy_journal_block()
{
	image=$1
	logical=$2
	output=$3
	journal_block "$image" "$logical"
	dd if="$image" of="$output" bs="$CURRENT_BLOCK_SIZE" \
	    skip="$JOURNAL_BLOCK" count=1 status=none
}

replace_journal_block()
{
	image=$1
	logical=$2
	input=$3
	journal_block "$image" "$logical"
	dd if="$input" of="$image" bs="$CURRENT_BLOCK_SIZE" \
	    seek="$JOURNAL_BLOCK" count=1 conv=notrunc status=none
}

expect_replay_failure_unchanged()
{
	image=$1
	before=$(sha256 -q "$image")
	run_fsck -fy "$image" "$case_dir/fsck.log"
	if [ "$FSCK_STATUS" -eq 0 ]; then
		fail "fsck_ext4fs accepted a malformed journal"
	fi
	[ "$FSCK_STATUS" -eq 8 ] ||
	    fail "malformed journal returned status $FSCK_STATUS, expected 8"
	after=$(sha256 -q "$image")
	[ "$before" = "$after" ] || fail "failed replay modified the image"
	grep -q 'JOURNAL REPLAY FAILED' "$case_dir/fsck.log" ||
	    fail "missing journal failure diagnostic"
}

test_basic_replay()
{
	format=$1
	open_command=$2
	case_dir=$work/$format
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 X
	{
		printf '%s\n' "$open_command"
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_nocsum()
{
	test_basic_replay nocsum journal_open
}

test_csum_v2()
{
	test_basic_replay csum-v2 'journal_open -c -v 2'
}

test_csum_v3()
{
	test_basic_replay csum-v3 'journal_open -c -v 3'
}

test_escape()
{
	case_dir=$work/escape
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	printf '\300\073\071\230' >"$case_dir/payload"
	dd if=/dev/zero bs=4092 count=1 status=none | tr '\000' E \
	    >>"$case_dir/payload"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_revoke()
{
	case_dir=$work/revoke
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 R
	dd if=/dev/zero of="$case_dir/zero" bs=4096 count=1 status=none
	: >"$case_dir/empty"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_write -r %s %s\n' "$FREE_RANGE" \
		    "$case_dir/empty"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	grep -q 'journal revoke: 1 blocks revoked' "$case_dir/fsck.log" ||
	    fail "revoke record was not processed"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 \
	    "$case_dir/zero"
	verify_e2fsck "$case_dir/image"
}

test_multi_descriptor()
{
	case_dir=$work/multi-descriptor
	mkdir "$case_dir"
	create_image "$case_dir/image" 1024
	find_free_blocks "$case_dir/image" 130
	make_payload "$case_dir/payload" 1024 130 M
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	descriptors=$("$DEBUGFS" -R logdump "$case_dir/image" 2>&1 |
	    grep -c 'type 1 (descriptor block)')
	[ "$descriptors" -ge 3 ] || fail "fixture has fewer than 3 descriptors"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 1024 "$FREE_FIRST" 130 \
	    "$case_dir/payload"
	verify_e2fsck "$case_dir/image"
}

test_read_only()
{
	case_dir=$work/read-only
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 N
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	before=$(sha256 -q "$case_dir/image")
	run_fsck -fn "$case_dir/image" "$case_dir/fsck.log"
	if [ "$FSCK_STATUS" -eq 0 ]; then
		fail "read-only fsck accepted a journal that requires replay"
	fi
	[ "$FSCK_STATUS" -eq 8 ] ||
	    fail "read-only replay returned status $FSCK_STATUS, expected 8"
	after=$(sha256 -q "$case_dir/image")
	[ "$before" = "$after" ] || fail "read-only validation modified image"
	grep -q 'journal validates but must be replayed with write access' \
	    "$case_dir/fsck.log" || fail "missing read-only replay diagnostic"
}

test_bad_data_checksum()
{
	case_dir=$work/bad-data-checksum
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 X
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	flip_journal_byte "$case_dir/image" 2 0 1
	expect_replay_failure_unchanged "$case_dir/image"
}

test_incomplete_transaction()
{
	case_dir=$work/incomplete
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 I
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	journal_block "$case_dir/image" 3
	dd if=/dev/zero of="$case_dir/image" bs=4096 \
	    seek="$JOURNAL_BLOCK" count=1 conv=notrunc status=none
	expect_replay_failure_unchanged "$case_dir/image"
}

test_validation_atomicity()
{
	case_dir=$work/validation-atomicity
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 2
	set -- $FREE_BLOCKS
	first=$1
	second=$2
	make_payload "$case_dir/first" 4096 1 A
	make_payload "$case_dir/second" 4096 1 B
	dd if=/dev/zero of="$case_dir/zero" bs=4096 count=2 status=none
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$first" "$case_dir/first"
		printf 'journal_write -b %s %s\n' "$second" "$case_dir/second"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	flip_journal_byte "$case_dir/image" 5 0 1
	expect_replay_failure_unchanged "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$first" 2 "$case_dir/zero"
}

test_block_sizes()
{
	root_dir=$work/block-sizes
	mkdir "$root_dir"
	for size in 1024 2048 4096; do
		case_dir=$root_dir/$size
		mkdir "$case_dir"
		create_image "$case_dir/image" "$size"
		find_free_blocks "$case_dir/image" 1
		make_payload "$case_dir/payload" "$size" 1 B
		{
			printf 'journal_open -c -v 3\n'
			printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
			    "$case_dir/payload"
			printf 'journal_close\n'
		} >"$case_dir/debugfs.cmd"
		run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
		replay "$case_dir/image"
		compare_blocks "$case_dir/image" "$size" "$FREE_FIRST" 1 \
		    "$case_dir/payload"
		verify_e2fsck "$case_dir/image"
	done
}

test_descriptor_boundary()
{
	root_dir=$work/descriptor-boundary
	mkdir "$root_dir"
	for count in 62 63; do
		case_dir=$root_dir/$count
		mkdir "$case_dir"
		create_image "$case_dir/image" 1024
		find_free_blocks "$case_dir/image" "$count"
		make_payload "$case_dir/payload" 1024 "$count" D
		{
			printf 'journal_open -c -v 3\n'
			printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
			    "$case_dir/payload"
			printf 'journal_close\n'
		} >"$case_dir/debugfs.cmd"
		run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
		descriptors=$("$DEBUGFS" -R logdump "$case_dir/image" 2>&1 |
		    grep -c 'type 1 (descriptor block)')
		if [ "$count" -eq 62 ]; then
			[ "$descriptors" -eq 1 ] ||
			    fail "62 tags did not fit in one descriptor"
		else
			[ "$descriptors" -eq 2 ] ||
			    fail "63 tags did not split into two descriptors"
		fi
		replay "$case_dir/image"
		compare_blocks "$case_dir/image" 1024 "$FREE_FIRST" "$count" \
		    "$case_dir/payload"
		verify_e2fsck "$case_dir/image"
	done
}

test_revoke_then_later_write()
{
	case_dir=$work/revoke-later-write
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/old" 4096 1 O
	make_payload "$case_dir/new" 4096 1 L
	: >"$case_dir/empty"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" "$case_dir/old"
		printf 'journal_write -r %s %s\n' "$FREE_FIRST" "$case_dir/empty"
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" "$case_dir/new"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	replay "$case_dir/image"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 "$case_dir/new"
	verify_e2fsck "$case_dir/image"
}

test_deleted_tag()
{
	case_dir=$work/deleted-tag
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 T
	dd if=/dev/zero of="$case_dir/zero" bs=4096 count=1 status=none
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	copy_journal_block "$case_dir/image" 3 "$case_dir/commit"
	replace_journal_block "$case_dir/image" 2 "$case_dir/commit"
	write_be16_journal "$case_dir/image" 1 18 12
	replay "$case_dir/image"
	grep -q 'journal replay: 0 blocks replayed' "$case_dir/fsck.log" ||
	    fail "deleted tag unexpectedly replayed a data block"
	compare_blocks "$case_dir/image" 4096 "$FREE_FIRST" 1 "$case_dir/zero"
	verify_e2fsck "$case_dir/image"
}

test_log_wraparound()
{
	case_dir=$work/log-wraparound
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 2
	set -- $FREE_BLOCKS
	first_target=$1
	second_target=$2
	make_payload "$case_dir/first" 4096 1 W
	make_payload "$case_dir/second" 4096 1 P
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$first_target" "$case_dir/first"
		printf 'journal_write -b %s %s\n' "$second_target" "$case_dir/second"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	for logical in 1 2 3 4 5 6; do
		copy_journal_block "$case_dir/image" "$logical" \
		    "$case_dir/journal.$logical"
	done
	read_be32_journal "$case_dir/image" 0 16
	maxlen=$JOURNAL_WORD
	read_be32_journal "$case_dir/image" 0 20
	journal_first=$JOURNAL_WORD
	wrap_start=$((maxlen - 3))
	replace_journal_block "$case_dir/image" "$wrap_start" \
	    "$case_dir/journal.1"
	replace_journal_block "$case_dir/image" $((wrap_start + 1)) \
	    "$case_dir/journal.2"
	replace_journal_block "$case_dir/image" $((wrap_start + 2)) \
	    "$case_dir/journal.3"
	replace_journal_block "$case_dir/image" "$journal_first" \
	    "$case_dir/journal.4"
	replace_journal_block "$case_dir/image" $((journal_first + 1)) \
	    "$case_dir/journal.5"
	replace_journal_block "$case_dir/image" $((journal_first + 2)) \
	    "$case_dir/journal.6"
	write_be32_journal "$case_dir/image" 0 28 "$wrap_start"
	replay "$case_dir/image"
	grep -q "journal scan: start block $wrap_start" "$case_dir/fsck.log" ||
	    fail "journal did not start at wrap boundary"
	compare_blocks "$case_dir/image" 4096 "$first_target" 1 \
	    "$case_dir/first"
	compare_blocks "$case_dir/image" 4096 "$second_target" 1 \
	    "$case_dir/second"
	verify_e2fsck "$case_dir/image"
}

test_sequence_wraparound()
{
	case_dir=$work/sequence-wraparound
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 2
	set -- $FREE_BLOCKS
	first_target=$1
	second_target=$2
	make_payload "$case_dir/first" 4096 1 S
	make_payload "$case_dir/second" 4096 1 Q
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$first_target" "$case_dir/first"
		printf 'journal_write -b %s %s\n' "$second_target" "$case_dir/second"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	write_be32_journal "$case_dir/image" 0 24 4294967295
	write_be32_journal "$case_dir/image" 1 8 4294967295
	write_be32_journal "$case_dir/image" 3 8 4294967295
	write_be32_journal "$case_dir/image" 4 8 0
	write_be32_journal "$case_dir/image" 6 8 0
	replay "$case_dir/image"
	grep -q 'end sequence 1 (2 transactions)' "$case_dir/fsck.log" ||
	    fail "transaction sequence did not wrap through zero"
	compare_blocks "$case_dir/image" 4096 "$first_target" 1 \
	    "$case_dir/first"
	compare_blocks "$case_dir/image" 4096 "$second_target" 1 \
	    "$case_dir/second"
	verify_e2fsck "$case_dir/image"
}

test_malformed_tags()
{
	root_dir=$work/malformed-tags
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 G
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	journal_block "$base_image" 2
	self_target=$JOURNAL_BLOCK

	for mutation in out-of-range unknown-flags missing-last self-target \
	    sequence-mismatch; do
		case_dir=$root_dir/$mutation
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		case "$mutation" in
		out-of-range)	write_be32_journal "$case_dir/image" 1 12 4294967295 ;;
		unknown-flags)	write_be16_journal "$case_dir/image" 1 18 32768 ;;
		missing-last)	write_be16_journal "$case_dir/image" 1 18 0 ;;
		self-target)	write_be32_journal "$case_dir/image" 1 12 "$self_target" ;;
		sequence-mismatch) write_be32_journal "$case_dir/image" 3 8 2 ;;
		esac
		expect_replay_failure_unchanged "$case_dir/image"
	done
}

test_checksum_failures()
{
	root_dir=$work/checksum-failures
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 C
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	for mutation in superblock descriptor data commit; do
		case_dir=$root_dir/$mutation
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		case "$mutation" in
		superblock)	flip_journal_byte "$case_dir/image" 0 100 1 ;;
		descriptor)	flip_journal_byte "$case_dir/image" 1 100 1 ;;
		data)		flip_journal_byte "$case_dir/image" 2 100 1 ;;
		commit)	flip_journal_byte "$case_dir/image" 3 100 1 ;;
		esac
		expect_replay_failure_unchanged "$case_dir/image"
	done

	case_dir=$root_dir/revoke-base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	: >"$case_dir/empty"
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -r %s %s\n' "$FREE_FIRST" "$case_dir/empty"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	case_dir=$root_dir/revoke
	mkdir "$case_dir"
	cp "$base_image" "$case_dir/image"
	flip_journal_byte "$case_dir/image" 1 16 1
	expect_replay_failure_unchanged "$case_dir/image"
}

test_malformed_revoke_lengths()
{
	root_dir=$work/revoke-lengths
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	: >"$case_dir/empty"
	{
		printf 'journal_open\n'
		printf 'journal_write -r %s %s\n' "$FREE_FIRST" "$case_dir/empty"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	for length in 15 17 4294967295; do
		case_dir=$root_dir/$length
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		write_be32_journal "$case_dir/image" 1 12 "$length"
		expect_replay_failure_unchanged "$case_dir/image"
	done
}

test_malformed_geometry()
{
	root_dir=$work/malformed-geometry
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 1
	make_payload "$case_dir/payload" 4096 1 Y
	{
		printf 'journal_open\n'
		printf 'journal_write -b %s %s\n' "$FREE_FIRST" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	read_be32_journal "$base_image" 0 16
	maxlen=$JOURNAL_WORD
	for mutation in block-size maxlen first start unsupported-feature uuid; do
		case_dir=$root_dir/$mutation
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		case "$mutation" in
		block-size)	write_be32_journal "$case_dir/image" 0 12 1024 ;;
		maxlen)	write_be32_journal "$case_dir/image" 0 16 4294967295 ;;
		first)		write_be32_journal "$case_dir/image" 0 20 0 ;;
		start)		write_be32_journal "$case_dir/image" 0 28 "$maxlen" ;;
		unsupported-feature)
			write_be32_journal "$case_dir/image" 0 40 2147483650
			;;
		uuid)		flip_journal_byte "$case_dir/image" 0 48 1 ;;
		esac
		expect_replay_failure_unchanged "$case_dir/image"
	done
}

test_randomized_replay()
{
	root_dir=$work/randomized-replay
	mkdir "$root_dir"
	iteration=0
	while [ "$iteration" -lt "$RANDOM_CASES" ]; do
		case_dir=$root_dir/$iteration
		mkdir "$case_dir"
		random_number
		case $((RANDOM_VALUE % 3)) in
		0) block_size=1024 ;;
		1) block_size=2048 ;;
		2) block_size=4096 ;;
		esac
		random_number
		case $((RANDOM_VALUE % 3)) in
		0) open_command=journal_open ;;
		1) open_command='journal_open -c -v 2' ;;
		2) open_command='journal_open -c -v 3' ;;
		esac
		random_number
		count=$((1 + RANDOM_VALUE % 16))
		# TODO: fsck_ext4fs currently rejects e2fsprogs checksum-v2
		# descriptors with multiple tags.  Keep randomized v2 cases
		# single-tag until that parser bug has a dedicated fix.
		[ "$open_command" != 'journal_open -c -v 2' ] || count=1
		random_number
		gap=$((RANDOM_VALUE % 16))
		create_image "$case_dir/image" "$block_size"
		find_free_blocks "$case_dir/image" $((count + gap))
		target=$((FREE_FIRST + gap))
		last=$((target + count - 1))
		if [ "$count" -eq 1 ]; then
			range=$target
		else
			range=$target-$last
		fi
		make_random_payload "$case_dir/payload" "$block_size" "$count"
		printf 'seed=%s block_size=%s format=%s count=%s target=%s\n' \
		    "$JOURNAL_SEED" "$block_size" "$open_command" "$count" \
		    "$range" >"$case_dir/parameters"
		{
			printf '%s\n' "$open_command"
			printf 'journal_write -b %s %s\n' "$range" "$case_dir/payload"
			printf 'journal_close\n'
		} >"$case_dir/debugfs.cmd"
		run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
		replay "$case_dir/image"
		compare_blocks "$case_dir/image" "$block_size" "$target" "$count" \
		    "$case_dir/payload"
		verify_e2fsck "$case_dir/image"
		iteration=$((iteration + 1))
	done
}

test_randomized_mutations()
{
	root_dir=$work/randomized-mutations
	mkdir "$root_dir"
	case_dir=$root_dir/base
	mkdir "$case_dir"
	create_image "$case_dir/image" 4096
	find_free_blocks "$case_dir/image" 8
	make_random_payload "$case_dir/payload" 4096 8
	{
		printf 'journal_open -c -v 3\n'
		printf 'journal_write -b %s %s\n' "$FREE_RANGE" \
		    "$case_dir/payload"
		printf 'journal_close\n'
	} >"$case_dir/debugfs.cmd"
	run_debugfs "$case_dir/image" "$case_dir/debugfs.cmd"
	base_image=$case_dir/image
	iteration=0
	while [ "$iteration" -lt "$MUTATION_CASES" ]; do
		case_dir=$root_dir/$iteration
		mkdir "$case_dir"
		cp "$base_image" "$case_dir/image"
		case $((iteration % 3)) in
		0) logical=1 ;;
		1) logical=10 ;;
		2) random_number; logical=$((2 + RANDOM_VALUE % 8)) ;;
		esac
		random_number
		case "$logical" in
		1|10)	within=$((12 + RANDOM_VALUE % (4096 - 12))) ;;
		*)	within=$((RANDOM_VALUE % 4096)) ;;
		esac
		random_number
		mask=$((1 << (RANDOM_VALUE % 8)))
		printf 'seed=%s logical=%s offset=%s mask=%s\n' "$JOURNAL_SEED" \
		    "$logical" "$within" "$mask" >"$case_dir/parameters"
		flip_journal_byte "$case_dir/image" "$logical" "$within" "$mask"
		expect_replay_failure_unchanged "$case_dir/image"
		iteration=$((iteration + 1))
	done
}

run_test()
{
	test_name=$1
	shift
	printf '%-44s' "$test_name"
	"$@"
	echo ' ok'
}

echo "random seed: $JOURNAL_SEED"
run_test 'journal replay without checksums' test_nocsum
run_test 'journal replay with checksum v2' test_csum_v2
run_test 'journal replay with checksum v3' test_csum_v3
run_test 'escaped journal data' test_escape
run_test 'revoke suppresses an earlier write' test_revoke
run_test 'later write survives an earlier revoke' test_revoke_then_later_write
run_test 'deleted descriptor tag' test_deleted_tag
run_test 'transaction spanning descriptor blocks' test_multi_descriptor
run_test 'descriptor capacity boundary' test_descriptor_boundary
run_test 'journal log block wraparound' test_log_wraparound
run_test 'transaction ID wraparound' test_sequence_wraparound
run_test 'read-only validation is non-mutating' test_read_only
run_test 'bad data checksum is non-mutating' test_bad_data_checksum
run_test 'incomplete transaction is non-mutating' test_incomplete_transaction
run_test 'validation precedes every home write' test_validation_atomicity
run_test '1K, 2K, and 4K filesystem blocks' test_block_sizes
run_test 'malformed descriptor tags and sequences' test_malformed_tags
run_test 'all journal checksum failure points' test_checksum_failures
run_test 'malformed revoke lengths' test_malformed_revoke_lengths
run_test 'malformed journal geometry and features' test_malformed_geometry
run_test 'seeded replay matrix' test_randomized_replay
run_test 'seeded checksum mutation sweep' test_randomized_mutations
